"""Increase password_hashed column size

Revision ID: 45bc648aaef7
Revises: bd45621ecae1
Create Date: 2025-03-14 19:49:17.812257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45bc648aaef7'
down_revision = 'bd45621ecae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
