"""Updated password_hashed to password

Revision ID: 8a7462da9e6c
Revises: 45bc648aaef7
Create Date: 2025-03-15 12:40:02.663583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a7462da9e6c'
down_revision = '45bc648aaef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('refresh_token', sa.String(length=500), nullable=True))
    op.drop_column('user', 'password_hashed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hashed', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
